### ISSUE TITLE
[BUG] 채널이 정상적으로 삭제되지 않음

### ISSUE THREAD

**Issue by windowdong11** [BeomJinNa/ft_irc#5]
## 버그 발생 과정
1. 새로운 채널에 참여 `JOIN #1`
2. 채널에서 나감 `JOIN #1`
3. 채널에 다시 참여 `JOIN #1`
4. 모드 변경 `MODE -i`

## 예상했던 결과
정상적으로 모드 변경이 됨.

## 실제 실행 결과
op권한이 없어 모드 변경이 되지 않음.

**Comment by windowdong11** [comment]
PART에서 마지막 유저를 삭제할 때, 채널이 삭제되지 않는 것으로 보입니다.
> 유저 삭제 이후, 채널의 액티브 유저 수를 확인 후에 채널을 삭제해야 하면 될거에요.

`DeleteChannel(channelId)` 메서드로 채널을 삭제했을 때에도 다시 채널을 생성할 때, `GetChannelIdByName(channelName)`으로 채널이 찾아지는 문제점이 있습니다.
> 이건 플랫폼 쪽 코드에서 해결되어야 할 듯 한데, mReferenceTableName에서 삭제해주면 될 것 같습니다.

관련 커밋 브랜치파서 올려보겠습니다.

**Comment by BeomJinNa** [comment]
마지막 유저 퇴장 시 채널 삭제는 레퍼런스에는 따로 없긴한데 보통은 지워주는거 같아요. join은 별개로 수정했습니다.
